enum ActionKind {
    Walking,
    Idle,
    Jumping
}
function SpawnCharecter () {
    Warrior = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
}
let Warrior: Sprite = null
let myMenu: miniMenu.MenuSprite = null
let MenuOpen = false
scene.setBackgroundImage(img`
    ccccccccccccccffffffffffffcccccccccccccccccccccccccffffffcccccccccccccccccfffccccccccccccccccfffffcccccccccccccccccccccfffffffffcccccccccccccccccccccccccffffff
    ccccccfccccc6ccffffffffcccccccccccccccccccccccccccccfffffcc77777ccc77777cffffccccccccccc77cccccfffcccc77777cccccccccccccfffffcccccccccccc6cccccccccccccccffffff
    cccccccccccccccfffffffcccc6cfcccccccccccccccccccccccffffc7cccccccccccccc77ffcccccccccccccccccccffccc7cccccccccccccccccfcffffccccccccccccccccccccccccccccccfffff
    cccccccccccccccccffffffccccccccccccccccccccccccccc7ccffcc7ccccccccccccccc7ffcccccccccccccccccccffcccccccccccccccccccccccffffccccccccccccccccccccccccccccccfffff
    ccccfcccccccccccccffffcccccccccccccccccccccccccccc7ccffcc7ccccccccccccccc7ffcccccccccc7ccccccccffcccccccccccccccccccccccffffccccccccccccccccccccccccccccccfffff
    cccccccfffccccccccffffcccccccccccccccccccccccccccc7ccffcc7ccccccccccccccc7ffcccccccccccccccc7ccffc7ccccccccccccccccccccccfffccccccccccccccccccccccccccccccfffff
    cccccccfffcccccccfffffcccccccccccccccccccccccccccccccffcc7ccccccccccccccc7ffcccccccccccccccc7ccffc77cccccccccccccccccccccfffccccccccccccccccccccccccccccccfffff
    cccccccfffcccccccffffffcccccccccccccccccccccccccc7cccffcc7ccccccccccccccc7ffcc7ccccccccccccc7ccffc77cccccccccccccccccccccffffcccccccccccccccccccccfffcccccfffff
    cccccccccccccccccffffffcccccccccccccccccccccccccc77ccffcc7ccccccccccccccc7cccc7ccccccccccccc7ccffccccccccccccccccccccccccfffccccccccccccccccccccccfffcccccfffff
    ccccccccccccccccffffffccccccccccccccccccccccccc7777ccfffc7cccccccccccccc77ccce7ccccccccccccc7ccfffcc7ccccccccccccccccccccfffcc7ccccccccccccccccccccffcccccfffff
    ccccccccccccccccfffffffccccccccccccccccccccccc7777ccffffcc77cccccccccc777cccce7ccccccccccccccccfffcccc7ccccccccccccccccffffffc7ccccccccccccccccccccccccccffffff
    cccccccccccccccffffffffccccccccccccccccccccc77777ccccfffcccccccccc77c777ccccce7ccccccccccccccccffccccccccccccccccccccccffffffccccccccccccccccccccccccccccffffff
    cccccccccccccffcfffffffcccc7c7777777777777777777cccffffffccccc7cc777777ecccccccccccccccccc777ecffccccccc7777777ccccccccffffffcccc7cccccccccccccccccccccffffffff
    ccccccccccccfffffffffffffffffffffffffffcccccccccfffffffffffccccccccccccccccccccce7777ccc77777ccffffcccccccccccccccccccfffffffffffffffffffffffffffffffffffffffff
    fcc8888c8fccfffffffffffffffffffffcccfffffffffffffffffffffffccccccccccccccccccceeebbb77cc7777ccccfffccccccccccccccccccffffffffffffffffffffffffffffffffffffffffff
    fffccfffffffffffffcccffffffffcccc66ccccffffffffffffffffcffffccccccccccccccccccceeeeeeecccccccccccfffffffcccccccfffffffffccccffffffffccc666cccffffffffffffffffff
    ffffffffffffffffffffffffffffffffcccccffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccffffffffcccfffffffffffffcccfffffffffffcccffffffffffffffffffffc
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccffccccccccccccccccccccccccccccccccfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
    fffffffffcccfffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccfffffccccccccfffffffffffffffffffffffffffffffffffffffffc8
    fffffffffcccfffffffffffffffffffcffffcccccfffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccfffffccccccccffffffffffffffffffcfffcffffffffffffffffffff
    fffffffffffffffffffffffffffffffccfffc666ccccffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccffffcccccccfffffffffffffffffccfffc666cccffffffffffffff
    ffffffffffffffffffffccccccffffffffffccccccccffffffffcccccccccccccccccccccccccccccccccccccceeeeeeeeeeeccccffffffcccccffffffcccccccfffffffffcccccfccfffffffffffff
    ffffffffffffffffffffccccccccfffffffcccccccccffffffffcccccccccccccccccccccccccccccccccccccc77eeeeeeeeeccccfffffffffcfffffffccccccccffffffffccccfffcfffffffffffff
    ffffffffffffffffffffffffcccc6cffffccccccccccffcfffffccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffccccccccccffffffccfffffcfffffffffffff
    fffffffffffffffffffffffccccc6cffffccccccccccffffccfffccccccccccccccccccccccceeecccccccccccccccccccccccccffffffffffffffffffcccccccc6cffffffccfffffffffffffffffff
    fffffffffffffffffffffffcccccccffffffccccccccffffccffcccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeecccccffffffffffffffffffccccccccccffffffccfffffffffffccffffff
    ffffffffffffffffffffffffccccccfffffffffffcffffffccffccccccccccccccccccccccceebe777eeeeeeeeeeeeeeeeeccccffccccccccfffffffffccccccccccffffffffffffffffffffffffccc
    fffffffffffffffffffffffffccccffffffffffffffffffcccffcccccccccccccccccccccceee477777eeeeeeeeeeeeeeeeeccccccccccccccfffffffffffffcccccffffffffffffffffffffffffccc
    fffffffffffffffffffffffffffffffffffffffffffffffcccffcccccccccccccccccccccceeb44eeeeeeeeeee777eeeeeeecccccfccccccccffffffccfffffffcfffffffffffffffffffffffffffff
    cccccccccccffffffcfffffffffffffffffffffffffffffffffccccccc77777777cccccccceeb4444444eeeeeeeecceeeeeeecccccccccccccccfffccffffffffffffffffffffffffffffffffffffff
    8ccccccccccccffffffffffffffffffccccccccccffffffffffccccccc77777777ccccccccceeb444444eeeeeeeeeeeeeeeeccccccccccccccccfffccfffffffffcffffccccccffffffffffffffffff
    cccccccccccccfffffffffffffc6ccccccc6ccccccfffffffffffccccc7777777777ccccccceee444444eeeeeeeeeeeeeeee777cccccccccccccffffffffffffcc6ccccc666c6ccffffffffffffffff
    cc88cccccccc6cffffffffffccccccccccccccccccffffffffffccccc77777777777cccccceee444444eee77cccccccccccceccccccccccccc6cfffffffffffcccccccccc66ccccccffffffffffffff
    f88cccccccccccfffffffffcccccccccccccccccccccffffffffccccc77777777777ccccceee444444eee77777eeeeeeeeeecccccccccccccccccffffffffccccccccccccccccc6ccffffffffffffff
    fff8ffcff8ccfffffffffffcccccccccccfcfcccccccffffffffcccc77777777777cccccceee44444eeee77777777ccccccccccccccccccccccccfffffffcccccccccccccfffcccccffffffffffffcc
    ffffcc8f88ccffffffffffccccccccccccccccccccccffffffffccccc77777777ccccccceee444444444e77777777eeeeeeeeccccccccccccccccfffffffcccccccccccccffccccccffffffffffffcc
    fff8ccff88ccffffffffffcffccccccccccfccccccccffffffffcccccccc777ccccccccceee444444444777777777eeeeeeeeccccccccccccccccfffffffcccccccccccccfffcccccfffffffffffff8
    ffffcfffffccffffffffcffcccccccccccccccccccccffffffffccccccccccccccccccceeb4444444444777777777cccccccccccccccccccccccffffffcccccccccccccccccccccccffffffffffffcc
    ffffffffffccffffffffcccccccccccccccccccccccccfffffffccccccccccccccccccceee4444444444e7c777777cccccccccccccccccccccccffffffcccccccccccccccccccccccfffffffffffffc
    fffffffffffcfffffffffccccccccccccccccccccccccfffffffccccc7cccccccccccccee44444444444e7c7eeeeccccccccccccccccccccccccffffffcccccccccccccccccccccccfffffffffffffc
    ffffffffffffffffffffffcccccccccccccccccccccccfffffffccccc7cccccccccccceee44444444444e7c7eeeeccccccccccccccccccccccccffffffcccccccccccccccccccccccfffffffffffffc
    fffffffffffffffffffffccccccccccccccccccccccccfffffffccccc77cccccccccccee444444444444eec7eeeeeeeeeeeeecccccccccccccccffffffcccccccccccccccccccccccffffffffffffff
    fffffffffffffffffffffccccccccccccccccccccccccfffffffccccccccccccccccccee44444444444eeeeccccccccccccccccccccffffccfffffffffccccccccccccccccccccccfffffffffffffff
    ffffffffffffffffffffffcfccccccccccccccccccccffffffffccccccccccccccccccee44444444444447eeccccccccceeecccccfcfffcfffffffffffcccccccccccccccccccccffffffffffffffff
    ffffffffffffffffffffffccccccccccccccccccccccffffffffccccccccccccccccccee44444444444444eeceeeeeeee7cccccccfffffffffffffffffffccccccccccccccccccccfffffffffffffff
    fcccffffffffffffffffffcccccccccccccccccccfffffffffffcccccccccccccccccceee4444444444444eeeeeeeeeeeeeeccccccffffffffffffffffffccccccccccccccccfffffffffffffffffff
    fcccffffffffffffffffffffcccffccccfccccccffffcfffffffffccccccccccccccccee444d44d4444444eeeeeeeeeeeeeeccccccccfcccffffffffffffffccfffccccffffffffffffffffffffffff
    cccc6ffc6cccffffffffffffffffffffffffffffffffccffffffcccc77777777cccccccee44d444444444becccccccccccccccccccccfcccccffffffffffffffffffffffffffffffffcffffffffffcc
    fccc8ffcccccffffffffffcccccccccccccccccfffffcccfffffcccccccccc77ccccccfff444dd44d44dcffc77ccccccccccccccccccfcccccccffffffffccccccccccccccccffffffccffffffffccc
    fffffffcccccffffffffffcccccccccccccccccfffffcccfffffccccccccccc7ccccccfffee4dd4dd44bfffc7777ccccccccccccccfffcccccccffffffffcccccccccccccccccfffffcccfffffffccc
    fffffffcccfffffffffffccccccccccccccccccccfffffffffffccccccccccccccccccffffcddd4dd4effffcececccccccccccfffffffcccccfffffffffcccccccccccccccccccfffffffffffffffff
    fffffffffffffffffffffcccccccccccccccccccffffffffffffccccccccccccccccccfffffffffffffffffcccecccccccccfffffffffcccccfffffffffccccccccccccccccccffffffffffffffffff
    fffffffffffffffffffffccccccccccccccccfffffffffffffffccccccccccccccccccfffffffffffffffffcccccccccccccfffffffffffffffffffffffccccccccccccccccffffffffffffffffffff
    fffcffffffffffffffffffffffccccccccffffffffffffffffffccccccccccccccccccccffffffffffffffcccccccccccccfffcccccccfffffffffffffffffffccccccccfffffffffffffffffffffff
    ffcccffffffffffffffffffffffcccccccffffffffffffffffffcccccccccccccccccccccfffffffffffffcccccccccccffffccccccccccffffffffffffffffffcccccfffffffffffffffffffffffff
    ffcccccccffffffffffffffffcffffffffffffffffccffffffffcccccffccccccccccccccffcffcccfffffcccccccccccfffcccccccccccccffffffffffffffcfffffffffffffffffffffffffffffff
    ffccccccccccffffffffffcccccffcfffffffffcccccffffffffffccccccfffccccccccccffcffecffffcccccccccccfffccccccccccccccccffffffffffcccccffffcffffffffcfccfffffffffffff
    fcccccccccccfffffffffccccccccccccffffffcccccffffffffffcfcccffffccccccccccffcfceccfffcccccccccccfffcccccccccccccccccfffffffffcccccccccccffffffcccccfffffffffffff
    ccccfcccffccfffffffffcccccccccccccccccccccccfffffffffffffffccccccccccccccfffffceefffccccc77cffffffccccccccccccccccccffffffffccccccccccccccccccccccfffffffffffff
    ccccfccccfccfffffffffccccccccccccccccccccccccffffffffffcccccc6cccccccccccccfccceefffccccc77cccffffccccccccccccccccccffffffffccccccccccccccccccccccfffffffffffff
    ffffffccffffffffffffcccccccccccccccccccccccccffffffffffccccccccccccccccccccfcceeeffffcccccccccffffccccccccccccccccccffffffccccccccccccccccccccccccccfffffffffc6
    fffffffcfffffffffffffcccccffccccccccccccccccffffffffccccccccccccccccfffffccffceeefffffcccccccccfffccccccccccccccccccffffffffcccccfccccccccccccccccfffffffffffcc
    ffffffffffffffffffffffccccffccccccccccccccccffffffffccccccccccccccccfffffcccffeeeffffccccccccccfffccccccccccccccccffffffffffcccccfccccccfffffffffffffffffffffcc
    fffffffffffffffffffffffffcffffffffffffffffffffffffffccccccccccccccccfffffcccffeeeffffccccccccccffffffcccccccccccccfffffffffffffcfffffffffffffffffffffffffffffcc
    ffffffffffffffffffffcfffffcccccccccccccccccccfffffffcccccccccccccccccffffcccffeccecfcccccccccccffffffffccccccccfffffffffffccffffccccccccccccccccccffffffffffffc
    fffffffffffffffffffcccffffccccccccccccccccccccffffffcccccccccccccccccccffccccccccccccccccccccccffffffffccccccccfffffffffffccffffccccccccccccccccccccffffffffffc
    f8ffcfcfffffffffffffcccccccccccccccccccccccccccfffffcccccccccccccccccccffffccbcbbbccccfccccccccffffffffccccfcfffffffffffffccccccccccccccccccccccccccfffffffffff
    c66c666ccfffffffffffcccccccccccccccccccccccccccfffffcccccccccccccccccccfffffccccccccfffccccccccfffffffccccccccccffffffffffccccccccccccccccccccccccccfffffffffff
    ccccccccccc6ffffffffffccccccccccccccccccccccfffffffffccccccccccccccccfffffffccccccccffffcccccccffffffcccccccccccccffffffffffccccccccccccccccccccccfffffffffffff
    ffffffffccc6cffffffffffccccccccccccccfffffffffffffffffcccccccccccccccffffcccffccccccfffcccccccffffffccccccccccccccffffffffffffccccccccccccccfffffffffffffffffff
    fffffffffccccc6cffffffffffccccfccccccffffffffffffffffffcccccccccccccfffffcccffeecccfffffcccccfffffffccccccccccccccffffffffffffffffccfffffffffffffffffffffffffff
    ffffffffffffcc6ccffffffffffffffffffffffccccccffffffffffffcccccccccccffffffffffeecffffffffcffffffffffffccccccccccccfffffffffffffffffffffffffffffffffffffffffffff
    cfcccccfffffcccccffffffffffffffffffffccccccccccfffffffffffffffccccffffffffffffeecfffffffffffffffffffffffffffffccccffffffffffffffffcfffffffffccccccccfffffffffff
    fcccccffccccffcccccfffffffcccccccccccccccccccccfffffffffffffcccccccfffffffffcceecffffffffffffffffffffffffffffffccffffffffffffffffccccccccccccccccc6ccffffffffff
    ffccccfccccccfccccccffcccccccccccccccccccccccccccfffffffffccccccccccccffffffeeecffccccccfffffffffffccccccccccfffffffffffffffccccccccccccccccccc6ccccccfffffffff
    fcccffccccccecffcccbcccccccccccccccccccccccccccccfffffffffccccccccccccffffffcccffcccccccccccffffffffcccccccccccfffffffffffffccccccccccccccccccccccccccfffffffff
    fcfffcccccccccccfcccbccccccccccccccccccccfcccccccfffffffcccccccccccccccfffffcccffcccccccccccfffffffccccccccccccffffffffffffcccccccccccccccccccccfcccccfffffffff
    fcffccccccccccecfccc66fccccccccccccccccccccccccccffffffffcccccccccccccfffffffcffccccccccccccfffffffccccccccccccccfffcffffffffccccccccccccccccccfffccccfffffffff
    cffcccccccccecfccffc66fccccccccccccccccccccccccccfffffffccccccccccccccffffffccffccccccccccccffffffffcccccccccccccfcccffffffffcccccccccccccccccfcfccccffffffffff
    fffccccccccccccceffcccffcccccccccccccccccccccccccffffffffccccccccccccccffffcccffcccccfffffffffffffffcccccccccccccfccfffffffffffcccccccccccccccfccfccccfffffffff
    fcccccccccccffeeeffcccfffccccccccccccccccccccccccffffffffccccccccccccccfffffffffffffffffffffffffffffffccccccccccffccffffffccfffcccccccccccccccccccccccfffffffff
    cccccccccccfcceeeffcccfffccccccccccccccccccccccccffffffffccccccccccccccffffcffffffffffffffffffffffffffffffffffffffffffffffcccffcccccccccccccccccccccccfffffffff
    cfcccccccccfccceeffcccffcfccccccccccccccccccccccfffffffffcccccccccccccfffffcfffcccccfffffffffffffffffffffffffccffffffffffccccccffccccccccccccccccccccffffffffff
    fccccccccffccccccffc6bfccffcccccccccccccccccccccffffffffffccccccccccccfffffffccccccccccccfffffffffffffccccffcccffffffffffccccccfffccccccccccccccccccfffffffffff
    fcccccccfcccccceeffcccfccfffcccccccccccccccccccfffffffccffccccccccfccfffffffccccccccccccccfffffffcccccccccffcccccfcccffffffcbddddddddddcccccccfffffffffffffffff
    ffcccccffcccccceeffcccffcffffffffffcccccccccfffffffffffccfffffffffffffffffffccccccccccccccccfffffcccfccfffffffffffffffffffffd1111111111bfffffffffffffffffffffff
    fcccccfcccccccecfffccceffffffffffffffffffffffffffffffffccfffffffffffffffffffccccccccccccccccfffffcccffcfffffffffffffffffffc1111111111111dbbffffffffffffffffffff
    cfccfffcccccccecffccccecffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccfffffffffffffffffffffffffffffbb11111111111111dbcccfffffffffffffffff
    ffccffccccccccecfccbccefffffcccccffffffffffffffffcccffffffffffffffcccccfffffccccccccccccccccffffffffffccccccfffffffffcccc11111111111111111dcccfffffffffffffffff
    fcfffcccccccccffc66ccfeffffcccccccffffffffffffffcccccccfffffffffffcccccffffffcccccccccccccccffffffffcccccccccccffffffccbd111111111111111111dddfffffffffffffffff
    fcffccccccccccfcc6bcffecffcccccccccccffffffcccccccccccccccfffccfccccccccccfffffffccccffcccfffffffffccccccccccccfffffcccb111111111111111111111dffffccccccccccccf
    cffccccccfffffcc6ccffcecffcccccccccccfffffcccccccccccccccfffffcccccccccccfffffffccccccffccfffffffffccccccccccccffffccccb1111111111111111111111bcfccccccccccccff
    ffccfffffffffccccfffffcfffcccccccccccfffffcccccccccccccccffffcccccccccccccffffffffccccffffffffffffcccccccccccccfffcfccdd111111111111111db11111dbccccccccccccfff
    fcccfffffffccccccfffffcfffccccccccccffffffcccccccccccccccffffcccccccccccccffcccffffffffcccccffffffcccccccccccccfffcccc11111111111111111bb111111bccccccccccccfff
    fffffffffcc666ccffffffcfffcccccccccfffffffcccccccccccccccffffcccccccccccccffcccffffffcccccccffffffcccccccccccccfffcccc11111111111111111bb111111bccccccccc8cffff
    ffffccccccc6cccfffffffcfffffffffffffffffffcffcccccccccccfffffffcccccccccccffcccfffcccccccccccffccfffccccccccccfffffcfcdddbdd111111dbbbbbb111dddbcfffffcccccffff
    ffff66666cccfffffffffccffffffffffffffffccffffffccccccfffffccffffffcccccccffffccfffffccccccccfffcccffccccccccfffccffffcbbcccb111111bcffcbd111dbbcfffffffffffffff
    66ccccccfffffffccfffffcffffffffffffffffccfcfffffffffffffffccfffffffffffffffffccffffffffffffffffcccfffffffffffffccffffcbccccccb111dbfffcbdbbdbbccfffffffffffffff
    66cccccffffffffccfffffcffcfffffffffffcccccccffffffffffffccccccffffffffffffcccccccffffffffffffcccccccfffffffffffcccccfcbcfccccb111bbfffcbdcbbbbcffcfffffffffffff
    fffffffffffffffffccffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcfffffffffcccccccccccccfccccb111dccbcfccccb111dbcccccccccccfcccfffffffffffff
    fffffffffffffffffccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdd11dbcccccbbbdd111ddbbccccccccfcccccccccbbccffff
    ffffffcffffffffffccffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1111dbcccccbbbd1111ddbbbcccfffffcccccccccb1ccffff
    ffffffcffffffffffccfffcffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccd11dbbcccccccccbccbbccb1dbcffffcccccfccfcc111cfffff
    fffffffffffffffffccfccfffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdddbbcccccccccccccddbcc1bcfffffccccccccfccd11ccffff
    ffffffffcffffffffccfccfffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbccbccccccccccbcc111fc1ccffffcccccccccfccbd1cccfff
    ffffffffcffffffffcccccfffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccffffffffbbdbcccfffcccffffff
    ffffffffcffffffffccccffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccfffffffcbbdbcccccffffcfffff
    ffffffffcffffffffcccffcffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccbcccccfcbccbddcccfffccfcbccccccc1ccccfffffff
    ffffffffcffffffccccfffcffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccbccd1dccdcfcccccddbcccdbdcccffffffff
    fffffffffffffffcccfffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccdcc111cb1ccccccb11dccc1dbcffffffffff
    ffffffffffffcccccffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1bcccccc1bccccccccccccccccccccd11cfccccfcffffffff
    ffffffffffffccccfffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1bccccccdbbbccccccccccccccbcccbbdbcffffcfffffffff
    ffffffcccccccffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1bccccccbbd1dccccccccccccb1ccccccbbffffffffffffff
    ccccccfffcccfffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1bcccbcccccbbbddcccccdbbccccccccccbdbccffffffffff
    ccccccfffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdbcccbccccccbbddccccbddbbcccccfffcb1bfcffffffffff
    ffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddccccccbbdd1ccccccccccbcfcccbbccffffcccfff
    ffffffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbcccccccccbcccccdbbccccccccbbcccccccccccc
    ffffffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccc1dbccccccccbbccccccccffff
    ffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbb1dccccccccccccccccccccccccccccccccffff
    ffffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbccccccccccccccccccccccccccccccccffff
    ffffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    fffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    fffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    fffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    fffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffccccfcccccc
    ffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffccccccccc
    fffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffcccccccc
    ffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    fffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccc
    ffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    fcccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccffffcccccccccccccc
    ccccccccccccccccccccccccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffccccccccfcccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccffccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccffccccccccccccccccc
    cccccccccccccccccccccccccccccccfffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffcccccccccccccccccc
    ccccccccccccccccccccccccccccccccfffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccccfffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffcccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffcccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffcccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
    ccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccf
    ccccccccccffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffcccffcccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    `)
if (!(MenuOpen)) {
    MenuOpen = true
    myMenu = miniMenu.createMenu(
    miniMenu.createMenuItem("", img`
        ..33333.33....................
        .42222222223..................
        422222222222..................
        4245555444222222222442223.....
        42454245452222222222222223....
        42454245552244542442224224....
        4245424545245445445224522eab3.
        4245555445244224545425422aaaa.
        4245442245244224544545222aaaab
        424542224524522454255422aaaaab
        424522224552555554245422aaaaa.
        42222222222222222224422aaaaab.
        .22222a2222222222245422aaaaa..
        ..34baaaa22ae222222422eaaaab..
        ....baaaaabaaaaaa22222aaaaa3..
        .....baaab.baaaaaa222aaaaab...
        ......3b.....bbbbbbbaaaaaab...
        ....................3aaaab....
        .....................3bab.....
        `),
    miniMenu.createMenuItem("", img`
        .....33................................................
        ..4222224.......343..34332223..........................
        .422222222.....422222222224223.........................
        3224555422244442222222222444224444...44443..4444.......
        42254445422222222542245224542222222422222222222224.....
        424542244222222225422452222222222222222222222222224....
        422542222245555455554555425445555522255554225555422b...
        322455542254225425422452245445422542452245445224422aab.
        322222454454445525422452245445422452542225425544222aaab
        222222245454444425422452245445422452542225422445422aaab
        224542254254224225422454245445422452452245444224422aaab
        422455554245555424554245425445222452255555445555422aaab
        32222222222222222222222222222222222244224542222222eaaaa
        .322222222222222222222222222222222224554542222222eaaaaa
        ...3222eaaae22eaaae2eaa22e2ee2aaae2222444222e22eaaaaaab
        .....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa22222222aaaaaaaaaaab
        ......baaaaaabaaaaaabaaaaaaaaaaaaaaaa2222eaaaaaaaaaaab.
        ........bbbb...bbbb...bbb.3bbbbbbb3..baaaaaaaaaabbbb...
        .......................................baaaaaab........
        ........................................3baabb.........
        `)
    )
    myMenu.setFrame(img`
        c c c c c c c c c c c c c c c 
        c e e 2 2 2 2 2 2 2 2 2 e e c 
        c e a a a a a a a a a a a e c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c a a a a a a a a a a a a a c 
        c e a a a a a a a a a a a e c 
        c e e 2 2 2 2 2 2 2 2 2 e e c 
        c c c c c c c c c c c c c c c 
        `)
}
